### ISSUE TITLE
Problems in simulation programs

### ISSUE THREAD

**Issue by ZH200002** [KTH-RPL-Planiacs/STL-RT-RRTstar#1]
Hello, there are two issues in the simulation program.
The 'get_random_node_ellipsis_sampling' function cannot be found in line 24 'from ellipsis import get_random_node_ellipsis_sampling'.
Line 1426 is missing the file 'stl_specifications/stl_tree_200_1500_wired_fragile_right. fill'.
May I ask how to solve these two problems？
<img width="754" alt="360截图1700101886104127" src="https://github.com/KTH-RPL-Planiacs/STL-RT-RRTstar/assets/136305664/053fd27c-4fde-4628-b9db-df3e9cae92ad">
<img width="820" alt="360截图17650101195449" src="https://github.com/KTH-RPL-Planiacs/STL-RT-RRTstar/assets/136305664/ad3c5994-6775-41a0-9da0-80d14663883a">

**Comment by allinard** [comment]
pushed missing files
